//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ant_test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ant_test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 353,136194331984
        ///352,451821862348
        ///349,714331983806
        ///546,129230769231
        ///618,672712550607
        ///676,844372469636
        ///413,360971659919
        ///280,592712550607
        ///205,996113360324
        ///188,886801619433
        ///125,924534412955
        ///76,6497165991903
        ///524,229311740891
        ///339,448744939271
        ///99,9183805668016
        ///223,105425101215
        ///257,324048582996
        ///90,3371659919028
        ///346,976842105263
        ///630,307044534413
        ///664,525668016194
        ///425,67967611336
        ///346,976842105263
        ///314,811336032389
        ///.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 512,365020242915
        ///511,372064777328
        ///507,40024291498
        ///792,378461538462
        ///897,631740890688
        ///982,032955465587
        ///599,745101214575
        ///407,111740890688
        ///298,8795951417
        ///274,055708502024
        ///182,703805668016
        ///111,211012145749
        ///760,603886639676
        ///492,505910931174
        ///144,971497975709
        ///323,703481781377
        ///373,351255060729
        ///131,07012145749
        ///503,428421052632
        ///914,511983805668
        ///964,15975708502
        ///617,618299595142
        ///503,428421052632
        ///456,759514170041
        ///.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 286,662024291498
        ///286,106477732794
        ///283,884291497976
        ///443,326153846154
        ///502,214089068826
        ///549,435546558704
        ///335,55012145749
        ///227,774089068826
        ///167,21951417004
        ///153,330850202429
        ///102,220566801619
        ///62,2212145748988
        ///425,548663967611
        ///275,551093117409
        ///81,1097975708502
        ///181,108178137652
        ///208,885506072874
        ///73,3321457489879
        ///281,662105263158
        ///511,658380566802
        ///539,435708502024
        ///345,54995951417
        ///281,662105263158
        ///255,551417004049
        ///.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 522,517894736842
        ///521,505263157895
        ///517,454736842105
        ///808,08
        ///915,418947368421
        ///1001,49263157895
        ///611,629473684211
        ///415,178947368421
        ///304,802105263158
        ///279,486315789474
        ///186,324210526316
        ///113,414736842105
        ///775,675789473684
        ///502,265263157895
        ///147,844210526316
        ///330,117894736842
        ///380,749473684211
        ///133,667368421053
        ///513,404210526316
        ///932,633684210526
        ///983,265263157895
        ///629,856842105263
        ///513,404210526316
        ///465,81052631579
        ///.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close_Button {
            get {
                object obj = ResourceManager.GetObject("Close_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close_Button_Invert {
            get {
                object obj = ResourceManager.GetObject("Close_Button_Invert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IKON {
            get {
                object obj = ResourceManager.GetObject("IKON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
